openapi: 3.1.0

info:
  title: OpenAPI Specification
  description: This is a sample OpenAPI specification for a simple API.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

paths:
  /pets:
    get:
      summary: Get all pets
      operationId: getPets
      tags:
        - pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
  /pets/{petId}:
    get:
      summary: Get a pet by ID
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A single pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Fluffy"
        tag:
          type: string
          example: "dog"
      required:
        - id
        - name

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Not Found"
      required:
        - error
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: "Validation failed"
      required:
        - error
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: "Resource not found"
      required:
        - error
    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          example: "Unauthorized"
      required:
        - error
    ForbiddenError:
      type: object
      properties:
        error:
          type: string
          example: "Forbidden"
      required:
        - error
    InternalServerError:
      type: object
      properties:
        error:
          type: string
          example: "Internal server error"
      required:
        - error
    ServiceUnavailableError:
      type: object
      properties:
        error:
          type: string
          example: "Service unavailable"
      required:
        - error