// This file is auto-generated by @hey-api/openapi-ts

export type Pet = {
    id: number;
    name: string;
    tag?: string;
};

export type ErrorResponse = {
    error: string;
};

export type ValidationError = {
    error: string;
};

export type NotFoundError = {
    error: string;
};

export type UnauthorizedError = {
    error: string;
};

export type ForbiddenError = {
    error: string;
};

export type InternalServerError = {
    error: string;
};

export type ServiceUnavailableError = {
    error: string;
};

export type GetPetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pets';
};

export type GetPetsErrors = {
    /**
     * Internal server error
     */
    500: {
        error?: string;
    };
};

export type GetPetsError = GetPetsErrors[keyof GetPetsErrors];

export type GetPetsResponses = {
    /**
     * A list of pets
     */
    200: Array<Pet>;
};

export type GetPetsResponse = GetPetsResponses[keyof GetPetsResponses];

export type GetPetByIdData = {
    body?: never;
    path: {
        /**
         * The ID of the pet to retrieve
         */
        petId: number;
    };
    query?: never;
    url: '/pets/{petId}';
};

export type GetPetByIdErrors = {
    /**
     * Pet not found
     */
    404: ErrorResponse;
    /**
     * Internal server error
     */
    500: InternalServerError;
};

export type GetPetByIdError = GetPetByIdErrors[keyof GetPetByIdErrors];

export type GetPetByIdResponses = {
    /**
     * A single pet
     */
    200: Pet;
};

export type GetPetByIdResponse = GetPetByIdResponses[keyof GetPetByIdResponses];

export type ClientOptions = {
    baseUrl: 'https://api.example.com/v1' | (string & {});
};